version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /opt/mosquitto:/mosquitto
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001   
    restart: always
  my-minio:
    image: minio/minio
    ports:
      - "7000:9000"
      - "7001:9001"
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: ManosHUA
      MINIO_ROOT_PASSWORD: 'z12#x1z29006'
    command: server --console-address ":9001" /data
    restart: always

volumes:
  minio-storage: {} 
